image: docker:19.03.13

variables:
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  REGISTRY_IMAGE_NAME: "shakecast/$CI_PROJECT_NAME"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build
  - test
  - release
  - deploy

.build-server:
  before_script:
    - docker build -f sc-server.dockerfile -t scserver:build .
    - docker run -d -e TESTING_APP_ENV='testing' -e SC_CI=1 -e SC_SMTP_FROM='shakecast.ci@github.com' -e SC_SMTP_PORT=1025 -e SC_SMTP_SERVER='localhost' --entrypoint=/bin/sh scserver:build
    - docker exec scserver:build python -m shakecast.tests.smtpserver &
    - docker exec scserver:build python -m pip install codecov

app-test:
  stage: test
  tags:
    - shakecast-dev
  only:
    - merge_requests
  #extends: .build-server
  script:
    - echo "SCRIPT IS HERE"
    #- docker exec -e scserver:build coverage run -m shakecast.tests.bundle
  after_script:
    #- docker exec scserver:build codecov
    #- docker stop scserver:build
