image: docker:19.03.13

variables:
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  REGISTRY_IMAGE_NAME: "shakecast/$CI_PROJECT_NAME"
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build
  - test
  - release
  - deploy

.compose:
  before_script:
    - apk add docker-compose

app-test:
  stage: test
  tags:
    - shakecast-dev
  only:
    - merge_requests
  extends: .compose
  script:
    - docker-compose up -d
    - docker exec -e SC_CI=1 -e SC_SMTP_FROM='shakecast.ci@github.com' -e SC_SMTP_PORT=1025 -e SC_SMTP_SERVER='localhost' shakecast-lite_web-server_1 python -m shakecast.app.startup
    - docker exec shakecast-lite_web-server_1 python -m shakecast.tests.smtpserver &
    - docker exec shakecast-lite_web-server_1 python -m pip install codecov
    - docker exec -e TESTING_APP_ENV='testing' shakecast-lite_web-server_1 coverage run -m shakecast.tests.bundle
  after_script:
    - docker exec shakecast-lite_web-server_1 codecov
    - docker-compose down
    - docker-compose rm
    

release-staging:
  stage: release
  extends: .compose
  tags:
    - shakecast-dev
  only:
    - master
  except:
    - schedules
  script:
    - docker-compose up --build -d
