image: docker:19.03.13

variables:
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  SERVER_REGISTRY_IMAGE_NAME: "shakecast/server"
  DOCKER_DRIVER: overlay2
  

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build
  - test
  - release
  - deploy

build-images:
  stage: build
  only:
    - merge_requests
  script:
    - docker build -f sc-server.dockerfile . -t ${CODE_REGISTRY_IMAGE}/${SERVER_REGISTRY_IMAGE_NAME}:${CI_PIPELINE_ID}
    - docker push ${CODE_REGISTRY_IMAGE}/${SERVER_REGISTRY_IMAGE_NAME}:${CI_PIPELINE_ID}

app-test:
  stage: test
  image: ${CODE_REGISTRY_IMAGE}/${SERVER_REGISTRY_IMAGE_NAME}:${CI_PIPELINE_ID}
  tags:
    - shakecast-dev
  only:
    - merge_requests
  before_script:
    - ./test_env.sh
  script:
    - coverage run -m shakecast.tests.bundle
    - codecov
