image: docker:19.03.13

variables:
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  REGISTRY_IMAGE_NAME: "shakecast/$CI_PROJECT_NAME"
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build
  - test
  - release
  - deploy

.build-server:
  before_script:
    - docker build -f sc-server.dockerfile -t scserver:build .
  after_script:
    - docker rm -f sc-server-build

build-images:
  stage: build
  script:
    - docker build -f sc-server.dockerfile -t scserver:build .

app-test:
  stage: test
  image: scserver:build
  tags:
    - shakecast-dev
  only:
    - merge_requests
  extends: .build-server
  before_script:
    - ./test_env.sh
  script:
    - coverage run -m shakecast.tests.bundle
    - codecov
