image: docker:19.03.13

include:
  - project: 'ghsc/hazdev/pipeline-build-template'
    ref: 'master'
    file: 'templates/library.yml'

variables:
  IMAGE_NAME: "$CI_PROJECT_NAME:${CI_PIPELINE_ID}"
  SERVER_REGISTRY_IMAGE_NAME: "shakecast/server"
  DOCKER_DRIVER: overlay2
  

services:
  - docker:19.03.13-dind

before_script:
  - docker info

stages:
  - build
  - test
  - release
  - deploy

build-test-images:
  stage: build
  tags:
    - shakecast-dev
  only:
    - merge_requests
  script:
    - docker build -f sc-server.dockerfile . -t shakecast-server:test

app-test:
  stage: test
  image: shakecast/centos
  tags:
    - shakecast-dev
  only:
    - merge_requests
  before_script:
    - cd ${CI_PROJECT_DIR}
    - chmod +x test_env.sh
    - ./test_env.sh
  script:
    - coverage run -m shakecast.tests.bundle
